### ISSUE TITLE
Where is the code to create the boxes?

### ISSUE THREAD

**Issue by mkinney** [gyptazy/vagrant-arm64-boxes#4]
Is there a link to the packer and/or scripts used to create the vagrant boxes?

**Comment by gyptazy** [comment]
Hey @mkinney,

unfortunately not. While a script could make sense for general distributions like Debian & RHEL based ones, there're too many manual tasks for BSD based systems or other ones like Nix or even Gentoo that needs a self compiled kernel with additional modules and drivers to run. Most ones are hand-crafted and only get updated from this initial template.

Hope this helps even it's probably not helpful...

Cheers,
gyptazy
