### ISSUE TITLE
Vagrant using gyptazy/ubuntu22.04-arm64 - need to resize HD

### ISSUE THREAD

**Issue by charles-pinkston** [gyptazy/vagrant-arm64-boxes#7]
Good evening,

I hope you might be able to help me out.  I'm running into two an issue trying to migrate an old Vagrant VM that had been running under virtualbox to use your ubuntu 22.04 vmware image so I can use it on a new Mac.  

In virtualbox, my old vm used the `vagrant-disksize` plugin to resize the virtual hard drive to allow for installation of project software. I can't seem to figure out how to resize the virtual harddrive under vmware-desktop.

If you don't know of any way to do it via vagrant, do you have any suggestions on building a customized box?  I've been looking into packer, but I'm not sure if that is the right approach for vmware.

**Comment by gyptazy** [comment]
Hey @charles-pinkston,

to resize the VM you may go in you VMware Desktop or VMware Fusion app to your VMs settings and increase the overall disk size to your desired amount. Afterwards, you need start the VM and to resize partition. As soon as the partition got extended you can resize your file system.

However, when you're talking about migrating from you old VBox VM to the new one keep in mind, that you may not mix binaries and libs from `amd64` arch with the `arm64` one. But of course everything else can be migrated like files etc.

Cheers,
gyptazy

**Comment by gyptazy** [comment]
Since there wasn't any further reply I'm closing this.
